services:
  postgresTemporario:
    image: postgres:17
    container_name: postgresTemporario
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  api:
    build: .
    container_name: api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgresTemporario
      - redis
    env_file:
      - .env
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
