spring:
  application:
    name: apihae

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*" # Confia em todos os hosts SSL (use com cautela)



server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN

app:
  jwt:
    secret: SuaChaveSecretaMuitoForteParaJWTQueDeveTerPeloMenos256BitsParaHS512_abcdefghijklmnopqrstuvwxy
    expiration-ms: 86400000