spring:
  application:
    name: apihae

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

server:
  port: ${PORT:8080}

frontend:
  reset:
    url: ${FRONTEND_URL}

app:
  allowed:
    origin: ${ALLOWED_ORIGIN}
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
