openapi: 3.0.0
info:
  title: Authentication and Email Verification API
  description: API for managing authentication and email verification.
  version: 1.0.0

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

tags:
  - name: Auth
    description: Operações relacionadas a autenticação dos funcionários
  - name: Employee
    description: Operações relacionadas ao funcionário

paths:
  /auth/send-email-code:
    post:
      summary: Send confirmation email
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "João Pedro"
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: senha123
      responses:
        200:
          description: Confirmation email sent successfully
        500:
          description: Failed to send confirmation email

  /auth/verify-email-code:
    post:
      summary: Verify email confirmation code
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                code:
                  type: string
                  example: "123456"
      responses:
        200:
          description: Code verified successfully
        400:
          description: Invalid or expired code
        500:
          description: Internal server error

  /auth/login:
    post:
      summary: Employee login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
        401:
          description: Invalid credentials

  /employee/get-professor/{id}:
    get:
      summary: Retrieve professor information by ID
      tags:
        - Employee
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Professor ID
          schema:
            type: string
      responses:
        200:
          description: Professor information retrieved successfully
        401:
          description: Unauthorized – invalid or missing token
        404:
          description: Professor not found

  /employee/delete-account/{id}:
    delete:
      summary: Delete professor account by ID
      tags:
        - Employee
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Account ID
          schema:
            type: string
      responses:
        200:
          description: Account deleted successfully
        404:
          description: Account not found

  /employee/update-account/{id}:
    put:
      summary: Update professor account information
      tags:
        - Employee
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Account ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
      responses:
        200:
          description: Account updated successfully
        404:
          description: Account not found
