services:
  api:
    image: nickolss/apihae:latest
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    privileged: true
    depends_on:
      - redis
    container_name: apiHae

  redis:
    image: redis:7.0
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/data
    container_name: redisHae
  
volumes:
  redis-data: